---
- name: install java on all servers like ubuntu , centos
  hosts: all
  become: yes
  tasks: 
    - name: install java on ubuntu
      apt:
        name: openjdk-8-jdk
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: install java on centos
      yum: 
        name: java-11-openjdk
        state: present
      when: ansible_facts['os_family'] == "RedHat"

